use crate::Error;
const HASH_SIZE:usize=1<<16;const MAX_DISTANCE:usize=u16::MAX as usize;const MIN_MATCH:usize=3;const MAX_MATCH:usize=u8::MAX as usize;const NONE:usize=usize::MAX;
pub(crate) fn search_depth(level:u8)->usize{[0,2,4,8,16,32,64,96,160,256][level as usize]}
fn hash_at(i:&[u8],p:usize)->usize{((i[p]as usize).wrapping_mul(251)^(i[p+1]as usize).wrapping_mul(31)^i[p+2]as usize)&(HASH_SIZE-1)}
fn insert(i:&[u8],p:usize,h:&mut[usize],prev:&mut[usize]){if p+MIN_MATCH>i.len(){return}let x=hash_at(i,p);prev[p]=h[x];h[x]=p}
fn find(i:&[u8],p:usize,h:&[usize],prev:&[usize],depth:usize)->(usize,usize){if p+MIN_MATCH>i.len(){return(0,0)}let mut c=h[hash_at(i,p)];let(mut bd,mut bl,mut tries)=(0,0,0);while c!=NONE&&tries<depth{let d=p-c;if d>MAX_DISTANCE{break}let mut l=0;let max=MAX_MATCH.min(i.len()-p);while l<max&&i[c+l]==i[p+l]{l+=1}if l>bl&&l>=MIN_MATCH{bl=l;bd=d;if l==max{break}}c=prev[c];tries+=1}(bd,bl)}
pub(crate) fn encode_lz(i:&[u8],depth:usize)->Vec<u8>{let mut o=Vec::with_capacity(i.len());let mut h=vec![NONE;HASH_SIZE];let mut prev=vec![NONE;i.len()];let mut p=0;while p<i.len(){let fp=o.len();o.push(0);let mut flags=0;for bit in 0..8{if p==i.len(){break}let(d,l)=find(i,p,&h,&prev,depth);if l>=MIN_MATCH{flags|=1<<bit;o.extend_from_slice(&(d as u16).to_le_bytes());o.push(l as u8);for x in p..p+l{insert(i,x,&mut h,&mut prev)}p+=l}else{o.push(i[p]);insert(i,p,&mut h,&mut prev);p+=1}}o[fp]=flags}o}
pub(crate) fn decode_lz(payload:&[u8],expected:usize)->Result<Vec<u8>,Error>{let mut o=Vec::with_capacity(expected);let mut p=0;while o.len()<expected{let flags=*payload.get(p).ok_or(Error::Truncated)?;p+=1;for bit in 0..8{if o.len()==expected{break}if flags&(1<<bit)==0{o.push(*payload.get(p).ok_or(Error::Truncated)?);p+=1}else{if p+3>payload.len(){return Err(Error::Truncated)}let d=u16::from_le_bytes([payload[p],payload[p+1]])as usize;let l=payload[p+2]as usize;p+=3;if d==0||d>o.len()||l<MIN_MATCH||o.len().saturating_add(l)>expected{return Err(Error::InvalidMatch)}for _ in 0..l{let s=o.len()-d;o.push(o[s])}}}}if p!=payload.len(){return Err(Error::TrailingData)}Ok(o)}
pub(crate) fn encode_rle(i:&[u8])->Vec<u8>{let mut o=Vec::new();let mut p=0;while p<i.len(){let v=i[p];let mut n=1;while p+n<i.len()&&i[p+n]==v&&n<255{n+=1}o.push(n as u8);o.push(v);p+=n}o}
pub(crate) fn decode_rle(p:&[u8],expected:usize)->Result<Vec<u8>,Error>{if !p.len().is_multiple_of(2){return Err(Error::InvalidRun)}let mut o=Vec::with_capacity(expected);for pair in p.as_chunks::<2>().0{let n=pair[0]as usize;if n==0||o.len().saturating_add(n)>expected{return Err(Error::InvalidRun)}o.extend(std::iter::repeat_n(pair[1],n))}if o.len()!=expected{return Err(Error::LengthMismatch{expected,actual:o.len()})}Ok(o)}
pub(crate) fn crc32(i:&[u8])->u32{let mut crc=u32::MAX;for &b in i{crc^=b as u32;for _ in 0..8{let mask=0u32.wrapping_sub(crc&1);crc=(crc>>1)^(0xedb8_8320&mask)}}!crc}
